version: "3.9"
services:
  db:
    image: postgres:16
    container_name: gatorgrades-db
    environment:
      POSTGRES_DB: gatorgrades
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gatorgrades-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gatorgrades
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: gatorgrades-frontend
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
